### ISSUE TITLE
Homepage: Get in Touch and arrow icon no longer aligned after re-sizing the browser to a certain dimension.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Aquarama-Marina#25]
![image](https://cloud.githubusercontent.com/assets/12791909/12907995/1850bd46-cf2d-11e5-8132-cdd3c312c1e2.png)

**Comment by ermatitan** [comment]
Please add the fix up to 320 px width

**Comment by wajahat-titan** [comment]
![screen-shot](https://cloud.githubusercontent.com/assets/16283336/12971783/c6f910da-d0c4-11e5-9d61-24b2718edd13.jpg)
My side its working fine from port 306

**Comment by ermatitan** [comment]
I'm using chrome while selecting the dimension below:

![image](https://cloud.githubusercontent.com/assets/12791909/13037853/a35cdabe-d3c4-11e5-939d-5eb4f0937635.png)
