### ISSUE TITLE
General : truncated text were displayed in repeater field. See Services and Weather page repeater fields. 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Aquarama-Marina#43]
![image](https://cloud.githubusercontent.com/assets/12791909/12969044/ae70e0f6-d0b5-11e5-866d-2bcfc20f8de7.png)

**Comment by wajahat-titan** [comment]
Dashboard styling  is not a part of developer. Please confirm with TL and Jolene to change the ACF plugin styles.

**Comment by wajahat-titan** [comment]
As per the Bernard comments this should be closed.

Bernard Salas:
Hmm, I don't believe it's an issue unless it's seriously hindering functionality
Can it be ignored for now since it needs overwriting default plug-in styles?
Yes, please don't touch it for now
